http response header

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,21 +1,88 @@
 #!/usr/bin/env bash
 # Get the hostname
-var=$(hostname)
+# Duplicate web-01 to web-02
+# These scripts represent an upgrade from the previous web server configuration...
 
-# Define the string for adding the custom header and rewrite rule
-string="server {\n\tadd_header X-Served-By $var;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
+# Uncomment to see the script run in action
+#set -x
 
-# Update package lists and install Nginx
-sudo apt-get update -y
-sudo apt-get install nginx -y
+echo -e "Updating and performing some minor checks...\n"
 
-# Create index.html and custom_404.html
-echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html > /dev/null
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
+function install() {
+	command -v "$1" &> /dev/null
 
-# Update Nginx configuration to add custom header and rewrite rule
-sudo sed -i "/^server {/a $string" /etc/nginx/sites-available/default
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
 
-# Start Nginx service
-sudo service nginx restart
+install nginx # Install nginx
 
+echo -e "\nSetting up some minor configurations.\n"
+
+# Allowing nginx through the firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Granting user ownership of website files for easier editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+
+# Create directories if not already present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+
+# Create a new index file
+echo "Hello World!" > /var/www/html/index.html
+
+# Create a new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# Backup the default server configuration file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+# Configure the server block for nginx
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
+
+# Apply the server configuration to the nginx default site
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+# Restart or start nginx service based on its running status
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
